[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
anyhow.workspace = true
async-sse = "5.1.0"
async-std = "1.12.0"
bincode = "1.3.3"
chrono = "0.4.26"
crux_core = { version = "0.6" }
crux_http = { version = "0.3" }
crux_macros = { version = "0.3" }
derive_more = "0.99.17"
futures = "0.3.28"
lazy_static = "1.4.0"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.99"
thiserror = "1.0.40"
uniffi = "0.24.1"
url = "2.4.0"
uuid = { version = "1.4.0", features = ["v4", "wasm-bindgen", "js"] }
wasm-bindgen = "0.2.87"
ethers = { version = "2.0.7" }

[dev-dependencies]
assert_let_bind = "0.1.1"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.24.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.24.1", features = ["build"] }
